api:
  internal: http://bms-api.svc:8080
  external: https://bms-api.prod8.bip.va.gov
log_level: warn
reports:
  every: 900 # 15m
  purge_older_than: 86400 # 24h
redis: redis://localhost:6379
uris: {}
worker:
  pid_file: <%= File.expand_path('run/worker.pid', __dir__) %>
