log_level: debug
url_options: &url_defaults
  headers:
    Cookie: "<%= File.read(File.expand_path('local/_oauth2_proxy', __dir__)).chomp %>"
email:
  approved:
    - '^.*@bah\.com$'
    - '^.*@va\.gov$'
  distro:
    to: 'alexander.loy@va.gov'
  manner: smtp
  options:
    address: 'localhost'
    port: 1025
keep_results: 5
kubernetes:
  url: https://api.prod8.bip.va.gov:443
  auth_options:
    bearer_token: <%= File.read(File.expand_path('local/k8_token', __dir__)).chomp %>
  ssl_options:
    ca_file: <%= File.expand_path('local/ca.crt', __dir__) %>
prometheus:
  <<: *url_defaults
  url: https://prometheus.prod8.bip.va.gov:443
uris:
  api_server: https://api.prod8.bip.va.gov/healthz
  consul: https://consul.prod8.bip.va.gov/v1/status/leader
  grafana: https://grafana.prod8.bip.va.gov/api/health
  idm: https://idm.prod.bip.va.gov/ipa/ui/
  kibana: https://kibana.prod8.bip.va.gov/status
  vault:
    uri: https://vault.prod8.bip.va.gov/v1/sys/health?standbyok
    type: response_code
    response_codes:
      429: STANDBY
      472: RECOVERY MODE
      473: PERFORMANCE STANDBY
      501: UNINITIALIZED
      503: SEALED
nexus:
  repos:
    prod: 'https://container-registry.prod8.bip.va.gov/'
    stage: 'https://container-registry.stage8.bip.va.gov/'
worker:
  sleep: 60
