debug: false
uris:
  api_server: https://api.prod8.bip.va.gov/healthz
  consul: http://prod9-consul.vault:8500/v1/status/leader
  dex: http://dex.auth:5556/healthz
  elastic_search:
    uri: http://prod8-elasticsearch-client.logging:9200/_cluster/health
    type: json
    value: status
  grafana: http://prod8-grafana.monitoring/api/health
  kibana: http://prod8-kibana.logging:443/status
  vault: http://prod8-vault.vault:8200/v1/sys/health?standbyok
email:
  approved:
    - /.*@bah\.com/
    - /.*@va\.gov/
  smtp:
    host: smtp.va.gov
    port: 25
prometheus:
  url: http://prod8-prometheus-operator-prometheus.monitoring.svc.prod8:9090
worker:
  sleep: 1800
