uris:
  api_server: https://api.prod8.bip.va.gov/healthz
  consul: http://prod8-consul.vault:8500/v1/status/leader
  dex: http://dex.auth:5556/healthz
  elastic_search:
    uri: http://prod8-elasticsearch-client.logging:9200/_cluster/health
    type: json
    value: status
  idm: https://idm.prod.bip.va.gov/ipa/ui/
  grafana: http://prod8-grafana.monitoring/api/health
  kibana: http://prod8-kibana.logging:443/status
  vault: http://prod8-vault.vault:8200/v1/sys/health?standbyok
email:
  whitelist:
    - /.*@bah\.com/
    - /.*@va\.gov/
  distro:
    to:
      - E_BIP_Platform_Prod_HealthCheck@bah.com
    cc:
      - alexander.loy@va.gov
      - jeffrey.jensen2@va.gov
  smtp:
    host: smtp.va.gov
    port: 25
prometheus:
  url: http://prod8-prometheus-operator-prometheus.monitoring.svc.prod8:9090
results:
  retain: 100
worker:
  sleep: 1800
