email:
  approved:
    - '^.*@approved\.com$'
    - '^.*@alsoapproved\.con$'
  distro:
    to: 'corporate.suit@approved.com'
  test: true
keep_results: 5
uris:
  api_server: https://api.prod8.bip.va.gov/healthz
  consul: http://prod8-consul.vault:8500/v1/status/leader
  dex: http://dex.auth:5556/healthz
  elastic_search:
    uri: http://prod8-elasticsearch-client.logging:9200/_cluster/health
    type: json
    value: status
  grafana: http://prod8-grafana.monitoring/api/health
  idm: https://idm.prod.bip.va.gov/ipa/ui/
  kibana: http://prod8-kibana.logging:443/status
  vault:
    uri: http://prod8-vault.vault:8200/v1/sys/health?standbyok
    type: response_code
    response_codes:
      429:
        text: STANDBY
        health: 'pass'
      472:
        text: 'RECOVERY MODE'
        health: 'fail'
      473:
        text: 'PERFORMANCE STANDBY'
        health: 'fail'
      501:
        text: 'UNINITIALIZED'
        health: 'fail'
      503:
        text: 'SEALED'
        health: 'fail'
kubernetes:
  url: https://kubernetes.default.svc
  auth_options:
    bearer_token: 'ImaBearRAwR'
  ssl_options: {}
nexus:
  repos:
    prod: 'https://container-registry.prod8.bip.va.gov/'
    stage: 'https://container-registry.stage8.bip.va.gov/'
prometheus:
  url: http://prod8-prometheus-operator-prometheus.monitoring:9090
worker:
  sleep: 60
