---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrole.name }}
rules:
  - apiGroups:
    - ""
    - extensions
    - metrics.k8s.io
    resources:
      - deployments
      - events
      - ingress
      - jobs
      - namespaces
      - nodes
      - pods
      - persistantvolumes
      - persistantvolumeclaims
      - services
    verbs:
      - get
      - watch
      - list
  - nonResourceURLs:
    - '*'
    verbs:
      - get
      - watch
      - list
