---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bms.name" . }}
  labels:
    {{- include "bms.labels" . | nindent 4 }}
data:
  production.yml: |-
    {{- .Files.Get "config/production.yml" | nindent 4 }}
