{{ $dot := . }}
{{ range $k, $v := .Values.cronjobs }}
---
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: {{ $v.name }}
  labels:
    {{- include "bms.labels" $dot | nindent 4 }}
spec:
  schedule: {{ include "bms.cronstring" . | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: {{ $dot.Values.serviceaccount.name }}
          restartPolicy: OnFailure
          containers:
          - name: curl
            image: byrnedo/alpine-curl
            command: ["curl", "--fail", "-XPOST", "-d 'id=latest'", {{ include "bms.emailurl" $dot | quote }}]
{{- end }}
