{{- if .Values.ingress.enabled  -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "bms.name" . }}
  labels:
    {{- include "bms.labels" . | nindent 4 }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretname }}
      hosts:
        - {{ .Values.ingress.host }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "bms.name" . }}
              servicePort: 5000
{{- end }}
