---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "bms.name" . }}
  labels:
    {{- include "bms.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.clusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ include "bms.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
