---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "bms.serviceAccountName" . }}
  labels:
    {{- include "bms.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
